Update sites.yml
kevquirk/512kb.club pull request #1275
Opened 2023-09-04 18:24 UTC by danielnuk

This PR is:

- [- ] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [- ] I used the uncompressed size of the site
- [- ] I have included a link to the GTMetrix report
- [- ] The domain is in the correct alphabetical order
- [- ] This site is not an ultra lightweight site
- [- ] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [- ] Check to confirm

```
- domain: danieln.uk
  url: https://danieln.uk
  size: 106
  last_checked: 2023-09-04
```

GTMetrix Report: https://gtmetrix.com/reports/danieln.uk/JzLwJpyC/

2023-09-04 18:59 UTC, garritfra requested changes

2023-09-04 18:59 UTC, garritfra commented on _data/sites.yml
> +  - domain: danieln.uk
This indentation seems off. Do you mind fixing it?

2023-09-04 19:53 UTC, danielnuk reviewed
Whoops. Updated :)

2023-09-05 17:22 UTC, closed without merging

2023-09-05 19:56 UTC, garritfra commented
Thanks! :)

2023-09-05 19:56 UTC, garritfra approved these changes

2023-09-05 19:57 UTC, garritfra commented
Any reason you closed this PR?