Update sites.yml
kevquirk/512kb.club pull request #1337
Opened 2023-11-06 17:16 UTC by r3k2

Add 3 new sites with less that 512kb
- https://gtmetrix.com/reports/hispagatos.org/6ljRXwyp/
- https://gtmetrix.com/reports/2600.madrid/NisSVMtR/
- https://gtmetrix.com/reports/rek2.hispagatos.org/64UmBsld/

This PR is:

- [ X] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [ ] I used the uncompressed size of the site
- [X ] I have included a link to the GTMetrix report
- [ ] The domain is in the correct alphabetical order
- [ ] This site is not an ultra lightweight site
- [ ] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [ X] Check to confirm

```
- domain: hispagatos.org
  url: https://hispagatos.org
  size: 256
  last_checked: 2023-11-06
```
```
- domain: 2600.madrid
  url: https://2600.madrid
  size: 1.64
  last_checked: 2023-11-06
```
```
- domain: rek2.hispagatos.org
  url: https://rek2.hispagatos.org
  size: 2.21
  last_checked: 2023-11-06
```

GTMetrix Report: 

- https://gtmetrix.com/reports/hispagatos.org/6ljRXwyp/
- https://gtmetrix.com/reports/2600.madrid/NisSVMtR/
- https://gtmetrix.com/reports/rek2.hispagatos.org/64UmBsld/

2023-11-06 17:28 UTC, r3k2 commented
says is failing on "- domain: kaki87.net" I did not add this domain

2023-11-07 07:38 UTC, garritfra requested changes

2023-11-07 07:38 UTC, garritfra commented on _data/sites.yml
> +4
```suggestion

```

2023-11-07 07:38 UTC, garritfra commented on _data/sites.yml
> +
```suggestion

```

2023-11-07 07:38 UTC, garritfra commented on _data/sites.yml
> +
```suggestion

```

2023-11-07 07:38 UTC, garritfra commented on _data/sites.yml
> +  size: 256
Uncompressed size should be used.

```suggestion
  size: 405
```

2023-11-07 07:38 UTC, garritfra commented on _data/sites.yml
> +  size: 1.64
```suggestion
  size: 4.97
```

2023-11-07 07:38 UTC, garritfra commented on _data/sites.yml
> +  size: 2.21
```suggestion
  size: 7.93
```

2023-11-07 07:49 UTC, garritfra approved these changes

2023-11-07 07:51 UTC, garritfra commented
Thanks! 🙂

2023-11-07 07:51 UTC, merged