Update sites.yml
kevquirk/512kb.club pull request #930
Opened 2022-08-23 19:44 UTC by Edwinliby

This PR is:

- [* ] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [* ] I used the uncompressed size of the site
- [ *] I have included a link to the GTMetrix report
- [ *] The domain is in the correct alphabetical order
- [ ] This site is not a ultra lightweight site
- [ *] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [ *] Check to confirm

```
- domain: ekuttan.me
  url: http://ekuttan.me/
  size: 192
  last_checked: 2022/08/24
```

GTMetrix Report: https://gtmetrix.com/reports/ekuttan.me/m7ATUHaY/

2022-08-24 22:12 UTC, garritfra requested changes
Please add the entry in alphabetical order. Thanks!

2022-08-25 06:31 UTC, Edwinliby commented
> Please add the entry in alphabetical order. Thanks!

2022-08-26 08:31 UTC, Edwinliby commented
> Please add the entry in alphabetical order. Thanks!

> added in alphabetical order.

2022-08-26 15:19 UTC, garritfra approved these changes

2022-08-26 15:19 UTC, merged